image: 
  name: dank123/kazoo
  username: dank123
  password: 123Password123
  email: dank@voxter.ca

pipelines:
  default:
    - step:
        script:
          - echo "This script runs on all branches that don't have any specific pipeline assigned in 'branches'."
  branches:
    3.22-fasttelecom:
      - step:
          script:
            - echo "Compiling Kazoo...."
            - make clean && make
            - echo "Making RPM..."