version: '3'
services:
  couchdb:
    image: couchdb
  rabbitmq:
    image: rabbitmq
  build:
    build:
      context: .
      dockerfile: Dockerfile.build
    domainname: local.voxter.net
    volumes:
      - .:/app
    depends_on:
      - couchdb
      - rabbitmq
