DELETE FROM qname;
ALTER TABLE qname AUTO_INCREMENT = 1;
INSERT INTO qname VALUES (-1,'ALL');
DELETE FROM qagent;
ALTER TABLE qagent AUTO_INCREMENT = 1;
INSERT INTO qagent VALUES (-1,'ALL');
DELETE FROM queue_stats;
ALTER TABLE queue_stats AUTO_INCREMENT = 1;
